name: Deploy Release via FTP

on:
  push:
    tags:
      - "v*"        # löst bei Tags wie v1.0.0 aus
  workflow_dispatch:  # manuell im Actions-Tab startbar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip project
        run: zip -r latest.zip .

      - name: Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./latest.zip
          server-dir: /minniark/
