name: Deploy Release via FTP

on:
  push:
    tags:
      - "v*"        # löst bei Tags wie v1.0.0 aus
  workflow_dispatch:  # manuell im Actions-Tab startbar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create latest.zip
        run: |
          rm -f latest.zip
          zip -r latest.zip . -x ".git/*" ".github/*" "node_modules/*"

      - name: Prepare upload dir
        run: |
          rm -rf upload && mkdir upload
          mv latest.zip upload/

      - name: FTP deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./upload/   # << muss mit / enden
          server-dir: /minniark/