name: Deploy Release via FTP

on:
  push:
    tags:
      - "v*"        # löst bei Tags wie v1.0.0 aus
  workflow_dispatch:  # manuell im Actions-Tab startbar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create latest.zip
        run: |
          rm -f latest.zip
          zip -r latest.zip . -x ".git/*" ".github/*" "node_modules/*"
      - name: Upload via FTP (curl IPv4, no EPSV)
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}   # am besten direkt die IPv4-Adresse!
          FTP_USER:   ${{ secrets.FTP_USER }}
          FTP_PASS:   ${{ secrets.FTP_PASSWORD }}
        run: |
          # Verzeichnis anlegen (ignorieren, wenn schon vorhanden)
          curl -sS --ipv4 --user "$FTP_USER:$FTP_PASS" "ftp://$FTP_SERVER/minniark/" || true
          # Upload: IPv4 erzwingen, EPSV (IPv6/Firewall-Problem) deaktivieren
          curl -sS --fail --ipv4 --disable-epsv \
               --ftp-method nocwd \
               -T latest.zip \
               --user "$FTP_USER:$FTP_PASS" \
               "ftp://$FTP_SERVER/minniark/latest.zip"